### PR TITLE
Fixed Lmc logo

### PR DESCRIPTION
**Pull request by tenerd**
New Lmc logo according to brandbook - https://www.lmc.eu/pro-media

### CODE REVIEW

**Comment by TomasVotruba** [comment]
I've consider that, yet I recall it looked inconsistent.
Could you please attach screenshot of this section with this logo?

**Comment by tenerd** [comment]
Yes, I can:

image

image

**Comment by tenerd** [comment]
Inconsistent or not, it is our current and only correct branding:)

**Comment by TomasVotruba** [comment]
Perfect @tenerd , looks fine to me. Thank you!

P.S.: I understand it's about branding, yet I'd prefer to be fitting into the design as well.

**Pull request merged**
